on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract package from commit message
        shell: bash
        run: |
          if ! [[ ${{ github.event.head_commit.message }} =~ \((.*?)\) ]]; then
            exit 0;
          fi
          
          PACKAGE=${BASH_REMATCH[1]} >> $GITHUB_ENV
          git checkout gh-pages

      - name: Private Composer Registry
        uses: and-that/private-composer-registry-action@v1.1.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          package_name: ${{ env.PACKAGE }}
      
      - name: Commit updates to GitHub Pages branch
        env:
          GIT_AUTHOR_NAME: Satis Updater
          GIT_AUTHOR_EMAIL: saits-updater[bot]@users.noreply.github.com
        run: |
          git config user.name ${GIT_AUTHOR_NAME}
          git config user.email ${GIT_AUTHOR_EMAIL}
          git add .
          git commit -m "Publish updates for ${{ env.PACKAGE}}"
          git push