on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "echo stuff"
        env:
          COMMIT_VAR: ${{ github.event.head_commit.message }}
          # COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ inputs.token }}"}}'
          COMPOSER_HOME: /tmp/.satis-build
          SATIS_CONFIG: satis.json
          GIT_AUTHOR_NAME: Satis Updater
          GIT_AUTHOR_EMAIL: saits-updater@noreply.github.io
        run: |
          # Extract Package
          if ! [[ $COMMIT_VAR =~ \((.*?)\) ]]; then
            exit 0;
          fi
          
          PACKAGE=${BASH_REMATCH[1]}

          mkdir /tmp/.satis-build
          echo "{}" > /tmp/.satis-build/composer.json

          composer g require composer/satis:dev-main --prefer-dist \
            --no-cache --no-progress --no-interaction -o \
            --ignore-platform-reqs


          php $COMPOSER_HOME/vendor/bin/satis build ${SATIS_CONFIG} -n . $PACKAGE

          rm -rf include/*
          cp -R build/* .
          rm -rf build/
          git config user.name $GIT_AUTHOR_NAME
          git config user.email $GIT_AUTHOR_EMAIL
          git add .
          git commit -m "Updated repository"
          git push
        shell: bash
